// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Todo struct {
	ID      int32       `json:"id"`
	Body    string      `json:"body"`
	EndDate time.Time   `json:"endDate"`
	UserID  int32       `json:"userID"`
	Done    interface{} `json:"done"`
}

type Users struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
}
